# The public surface of FloDR on the CPU with short fits: shapes, exact latent round trips, the
# density methods, the certificates, the scikit-learn contract and pickling. The paper's numbers
# are regenerated by scripts/regen, not checked here.

import pickle
import warnings

import numpy as np
import pandas as pd
import pytest
from sklearn.base import clone
from sklearn.exceptions import NotFittedError
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

from flodr import FloDR, TrainConfig, raw_recipe

N, ITERS = 500, 40


def blobs(n, d, k=4, seed=0):
    rng = np.random.default_rng(seed)
    c = rng.normal(size=(k, d)) * 4
    lab = rng.integers(0, k, n)
    return (c[lab] + rng.normal(size=(n, d))).astype(np.float32), lab


def short(**kw):
    return FloDR(device="cpu", random_state=0, max_iter=ITERS, verbose=False, **kw)


# 40 features are used as given, 10 are padded to 30 with per-cell noise columns
@pytest.fixture(scope="module", params=[40, 10], ids=["wide", "padded"])
def fitted(request):
    X, lab = blobs(N, request.param)
    return short().fit(X), X, lab


def test_recipe_defaults():
    cfg = raw_recipe()
    assert (
        cfg.iters == 6400
        and cfg.lr == pytest.approx(0.0025)
        and cfg.pad == 30
        and cfg.fine_eps == 0.25
    )
    assert (
        cfg.compile_edges
        and cfg.half_edges == "fp16"
        and cfg.edge_batch == -1
        and cfg.neg == 48
    )


def test_budget_rescales_step_size():
    # lr * iters is held at 16, capped at 0.02 below 800 steps; an explicit lr wins
    assert raw_recipe(iters=3200).lr == pytest.approx(0.005)
    c = raw_recipe(iters=100)
    assert c.lr == pytest.approx(0.02) and c.fine_lr == pytest.approx(0.008)
    assert raw_recipe(iters=800, lr=0.01).lr == 0.01
    assert not hasattr(TrainConfig(), "fine_last") and not hasattr(
        TrainConfig(), "freeze_at"
    )


def test_fit(fitted):
    m, X, _ = fitted
    assert m.embedding_.shape == (N, 2) and np.isfinite(m.embedding_).all()
    assert m.roundtrip_ < 1e-3
    assert m.n_iter_ == ITERS and m.n_features_in_ == X.shape[1]


def test_transform(fitted):
    m, X, _ = fitted
    Y = m.transform(X[:100])
    assert Y.shape == (100, 2) and np.isfinite(Y).all()
    if X.shape[1] >= 30:
        # unpadded inputs reproduce the layout; padded ones get zeros where training cells had noise
        np.testing.assert_allclose(Y, m.embedding_[:100], atol=1e-3)
    Yo = m.transform_opt(X[:30], steps=10)
    assert Yo.shape == (30, 2) and np.isfinite(Yo).all()


def test_latent_round_trip_is_exact(fitted):
    m, X, _ = fitted
    np.testing.assert_allclose(
        m.inverse_latent(m.transform_latent(X[:30])), X[:30], atol=1e-3
    )
    Xi = m.inverse_transform(m.embedding_[:30])
    assert Xi.shape == (30, X.shape[1]) and np.isfinite(Xi).all()


def test_density(fitted):
    m, X, _ = fitted
    s = m.score_samples(X[:50])
    assert s.shape == (50,) and np.isfinite(s).all()
    assert m.score(X[:50]) == pytest.approx(s.mean(), abs=1e-3)
    cs = np.asarray(m.conditional_spread(m.embedding_[:40], n_samples=8))
    assert cs.shape[0] == 40 and np.isfinite(cs).all()
    at = m.atypicality(n_samples=8)
    assert at.shape == (N,) and at.min() >= 0 and at.max() <= 1


# the certificates bin the layout and need a dozen cells in several bins, hence the larger fit
@pytest.fixture(scope="module", params=[40, 10], ids=["wide", "padded"])
def binned(request):
    X, lab = blobs(2000, request.param)
    return short().fit(X), lab


def test_certificates_run(binned):
    m, lab = binned
    assert "passed" in m.spread_calibration()
    field, cert = m.hidden_contrast(lab, n_perm=9, iters=100)
    assert np.isfinite(np.asarray(field, float)).all() and "passed" in cert
    diag = m.diagnostics(lab, n_perm=9, iters=100)
    assert {"spread", "hidden_contrast"} <= set(diag)


@pytest.mark.xfail(
    strict=True,
    reason="spread_calibration indexes an empty bin list when no bin holds a dozen "
    "cells; hidden_contrast returns undecided there",
)
def test_spread_calibration_without_populated_bins():
    X, _ = blobs(60, 12)
    assert short().fit(X).spread_calibration()["passed"] is None


def test_params():
    m = FloDR()
    assert set(m.get_params()) == {
        "n_components",
        "w",
        "density",
        "max_iter",
        "random_state",
        "device",
        "verbose",
        "advanced",
    }
    assert m.set_params(w=1.0).w == 1.0
    with pytest.raises(ValueError):
        m.set_params(pad=0)
    c = clone(short(advanced={"pad": 0}))
    assert c.get_params()["advanced"] == {"pad": 0}
    assert repr(short()).startswith("FloDR(")


@pytest.mark.parametrize(
    "kw",
    [
        dict(advanced={"padd": 0}),
        dict(n_components=2.0),
        dict(n_components=1),
        dict(max_iter=0),
        dict(w=-1),
    ],
)
def test_rejects_bad_parameters(kw):
    X, _ = blobs(100, 8)
    with pytest.raises(ValueError):
        FloDR(device="cpu", verbose=False, **kw).fit(X)


def test_input_checks():
    X, _ = blobs(200, 12)
    with pytest.raises(NotFittedError):
        FloDR().transform(X)
    m = short(advanced={"pad": 0}).fit(X)
    with pytest.raises(ValueError):
        m.transform(X[:, :11])
    Xn = X[:5].copy()
    Xn[0, 3] = np.nan
    with pytest.raises(ValueError):
        m.transform(Xn)
    assert list(m.get_feature_names_out()) == ["flodr0", "flodr1"]


def test_three_components():
    X, _ = blobs(300, 20)
    m = short(n_components=3).fit(X)
    assert m.embedding_.shape == (300, 3)
    np.testing.assert_allclose(
        m.inverse_latent(m.transform_latent(X[:20])), X[:20], atol=1e-3
    )


def test_without_density():
    X, _ = blobs(200, 12)
    m = short(density=False).fit(X)
    assert not hasattr(m, "score") and not hasattr(m, "score_samples")
    with pytest.raises(ValueError):
        m.spread_calibration()


def test_deprecations():
    X, _ = blobs(200, 12)
    with warnings.catch_warnings(record=True) as w:
        warnings.simplefilter("always")
        m = FloDR(device="cpu", verbose=False).fit(X, iters=20, progress=False)
        m.inverse_coords(m.transform_latent(X[:3]))
    assert m.n_iter_ == 20
    assert sum(issubclass(x.category, FutureWarning) for x in w) == 3


def test_sklearn_tools():
    X, _ = blobs(300, 16)
    base = short(advanced={"pad": 0})
    assert make_pipeline(StandardScaler(), clone(base)).fit(X).transform(
        X[:10]
    ).shape == (10, 2)
    # score is the held-out mean log density, so model selection needs no labels
    gs = GridSearchCV(clone(base), {"w": [1.0, 2.0]}, cv=2).fit(X)
    assert gs.best_params_["w"] in (1.0, 2.0)
    df = pd.DataFrame(X, columns=[f"g{i}" for i in range(16)])
    m = clone(base).set_output(transform="pandas").fit(df)
    out = m.transform(df.iloc[:5])
    assert isinstance(out, pd.DataFrame) and list(out.columns) == ["flodr0", "flodr1"]
    assert list(m.feature_names_in_) == list(df.columns)


@pytest.mark.parametrize(
    "rs",
    [None, 3, np.random.RandomState(3), np.random.default_rng(3)],
    ids=["none", "int", "RandomState", "Generator"],
)
def test_random_state_forms(rs):
    X, _ = blobs(150, 12)
    assert np.isfinite(
        FloDR(device="cpu", max_iter=10, verbose=False, random_state=rs)
        .fit(X)
        .embedding_
    ).all()


def test_seeded_fits_repeat():
    X, _ = blobs(200, 12)
    np.testing.assert_array_equal(short().fit(X).embedding_, short().fit(X).embedding_)


def test_pickle(fitted):
    m, X, _ = fitted
    back = pickle.loads(pickle.dumps(m))
    np.testing.assert_array_equal(back.transform(X[:20]), m.transform(X[:20]))
    np.testing.assert_allclose(back.score_samples(X[:20]), m.score_samples(X[:20]))
    np.testing.assert_array_equal(back.embedding_, m.embedding_)
