import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SCRIPTS = os.path.dirname(HERE)
ROOT = os.path.dirname(SCRIPTS)
SCORES = os.path.join(SCRIPTS, "cache", "heldout_benchmark.json")
OUT = os.path.join(ROOT, "paper", "heldout_opta_table.tex")

DS = [("mnist", r"\emph{MNIST} ($n=5000$, $d=784$, raw pixels; Euclidean)"),
      ("fmnist", r"\emph{Fashion-MNIST} ($n=5000$, $d=784$, raw pixels; Euclidean)"),
      ("paul15", r"\emph{paul15 (scRNA-seq)} ($n=2730$, $d=50$, HVG-1000 $\to$ PCA-50; Euclidean)"),
      ("drfp", r"\emph{Schneider 50k (reactions)} ($n=5000$, $d=2048$, DRFP, 2048 bits; Jaccard)")]
METHODS = [("flodr", "FloDR (ours)", "0.002--0.04"),
           ("flodr_optA", "FloDR + optA (ours)", "0.06--0.14"),
           ("umap", "UMAP transform", "0.9--13.4"),
           ("opentsne", "openTSNE transform", "0.5--11.3"),
           ("parametric_umap", "Parametric UMAP", "---"),
           ("pca2", "PCA-2", "$<$0.1"),
           ("knnmap", "kNN interp.", "0.03--10.7")]
METRICS = ("recall15", "trust15", "cpd")


def main():
    scores = json.load(open(SCORES))
    L = [r"% generated by scripts/plotting/tab_heldout_opta.py -- do not hand-edit",
         r"\begin{tabular}{@{}lrrrr@{}}", r"  \toprule",
         r"  Method & recall@15 & trust@15 & CPD ($\rho$) & place (s/1k) \\"]
    for ds, header in DS:
        L += [r"  \midrule", rf"  \multicolumn{{5}}{{@{{}}l}}{{{header}}} \\"]
        best = {f: max(scores[ds][m][f + "_mean"] for m, _, _ in METHODS
                       if m in scores[ds]) for f in METRICS}
        for key, name, place in METHODS:
            if key not in scores[ds]:
                continue
            a = scores[ds][key]
            cells = []
            for f in METRICS:
                inner = rf"{a[f + '_mean']:.3f} \pm {a[f + '_std']:.3f}"
                cells.append(rf"$\mathbf{{{inner}}}$" if a[f + "_mean"] == best[f]
                             else f"${inner}$")
            L.append(rf"  {name} & " + " & ".join(cells) + rf" & {place} \\")
    L += [r"  \bottomrule", r"\end{tabular}", ""]
    open(OUT, "w").write("\n".join(L))
    print("\n".join(L), flush=True)
    print(f"wrote {OUT}", flush=True)


if __name__ == "__main__":
    main()
